### PR TITLE
Fixed json decode, improved logging, updated config to remove compile warnings

### PR DESCRIPTION
**Pull request by CodeYouMust**
1. fixed json decode
2. improved logging usefulness
3. Updated config to remove compile time warnings
4. consolidated parameters in central location
5. Some additional refactoring.

### CODE REVIEW

**Review by dgilling — COMMENTED** [review]
lgtm, @dkm199 any comments?
Were we able to test with the policy here (https://www.moesif.com/implementation/log-http-calls-from-azure-api-management?platform=azure-management)? Or do I need to fix syntax?

**Review by dkm199 — APPROVED** [review]
lgtm

**Comment by dkm199** [comment]
checked with @CodeYouMust , ready to merge

**Comment by CodeYouMust** [comment]
> lgtm, @dkm199 any comments?
> Were we able to test with the policy here (https://www.moesif.com/implementation/log-http-calls-from-azure-api-management?platform=azure-management)? Or do I need to fix syntax?

I will send updated policy to you.

**Pull request merged**
